// Write a C++ Program to display the quadrilateral using stars(*)


#include <bits/stdc++.h>
using namespace std;
int main() {
    int n; // height of the quadrilateral
    cin >> n;
    for (int i = 1; i <= n; i++) {
        // print leading spaces
        for (int j = 1; j <= n - i; j++) {
            cout << " ";
        }
        // print stars
        for (int j = 1; j <= 2 * i - 1; j++) {
            cout << "*";
        }
        cout << endl;
    }
    for (int i = n - 1; i >= 1; i--) {
        // print leading spaces
        for (int j = 1; j <= n - i; j++) {
            cout << " ";
        }
        // print stars
        for (int j = 1; j <= 2 * i - 1; j++) {
            cout << "*";
        }
        cout << endl;
    }
    return 0;
}
